### ISSUE TITLE
en dashboard de fellows, actividades próximas, de qué depende?

### ISSUE THREAD

**Issue by hugovom** [GobiernoFacil/agentes-v2#114]
de la fecha de sesión? o de la fecha límite para realizar la evaluación?

**Comment by CarlosOsorio** [comment]
Depende de la fecha de inicio de la sesión, está sacando las que se encuentran dentro del día actual al siguiente mes.

**Comment by hugovom** [comment]
Pregunta, debería depender de la fecha de actividad?

**Comment by CarlosOsorio** [comment]
Si, esta sacando la lista en base a la fecha de cierre de la actividad y de apertura de la sesión.

**Comment by hugovom** [comment]
va, gracias

**Comment by hugovom** [comment]
Y dependen de que la evaluación haya sido completada?

**Comment by CarlosOsorio** [comment]
@hugovom No, eso si no esta implementado
