### ISSUE TITLE
Agregar sección de documentos cargados

### ISSUE THREAD

**Issue by hugovom** [GobiernoFacil/agentes-v2#123]
Entre lo que platiqué con los fellows de Sonora es que les gustaría una sección en la que puedan consultar lo que han cargado a la plataforma, creo que el perfil y enlace directo desde aprendizaje puede ser suficiente. @ArgentinaVelasco me ayudas con el diseño?

**Comment by CarlosOsorio** [comment]
@hugovom ¿Hace falta algo más aquí?

**Comment by hugovom** [comment]
@CarlosOsorio nada
