### ISSUE TITLE
Errores de dedo en contenido 

### ISSUE THREAD

**Issue by ArgentinaVelasco** [GobiernoFacil/agentes-v2#150]
http://apertus.org.mx/tablero/calificaciones/metodologia
A manera general la evaluación consta de exámenes en línea, trabajos individuales, participación en los **fotos** y trabajos por equipo. el correcto es **foros**

**Comment by ArgentinaVelasco** [comment]
http://apertus.org.mx/tablero/aprendizaje/seminario-1-identificacion-de-problematicas-sociales-en-el-marco-de-los-ods-y-alternativas-de-solucion-mediante-el-gobierno-abierto

Productos a desarrollar
Entrega del Ensayo Inicial individual Documento por equipos A partir de las mesas de trabajo del seminario, y los productos del mismo, **elaboarar** ... **ELABORAR**

**Comment by ArgentinaVelasco** [comment]
http://apertus.org.mx/tablero/aprendizaje/bienvenida
en la parte de sesión: Revisión de los **vídeos** **(VA SIN ACENTO)** de Bienvenida a los fellows por parte de las autoridades.

**Comment by ArgentinaVelasco** [comment]
http://apertus.org.mx/tablero/aprendizaje/curso-1-gobierno-abierto-y-los-ods/sesion-5-cierre-del-curso-1
en la descripción de objetivos: Presentar tu diagnóstico del entregable 1 a miembros **del** tu Secretariado Técnico Local y si es posible. **VA SIN LA "L"**

**Comment by ArgentinaVelasco** [comment]
http://apertus.org.mx/tablero/aprendizaje/seminario-1-identificacion-de-problematicas-sociales-en-el-marco-de-los-ods-y-alternativas-de-solucion-mediante-el-gobierno-abierto/presentaciones-de-expositores-y-evaluacion-del-seminario-1
el error está en Objetivo:
Contar con el material presentado por los **de** expositores durante el Seminario, así mismo evaluar la dinámica del evento. SOBRA EL **"DE"**

**Comment by hugovom** [comment]
Todos los errores son del equipo que realizó la carga, por lo que se los enviaré para su corrección.
