### ISSUE TITLE
Avisos a fellows: ¿se podrían enviar desde mensajes?

### ISSUE THREAD

**Issue by hugovom** [GobiernoFacil/agentes-v2#153]

**Comment by CarlosOsorio** [comment]
@hugovom Ya se envían correos a los fellows en la sección de Avisos, noticias y eventos, cada que se crea uno y se publica. ¿es cambiar los avisos para que lleguen a la parte de mensajes del fellow?

**Comment by hugovom** [comment]
exacto, ocurre que si llegan en avisos al parecer los ignoran…

**Comment by CarlosOsorio** [comment]
@hugovom Sí, se puede hacer, pero funcionaría como centro de notificaciones sin leer.
