### ISSUE TITLE
Tiempo 

### ISSUE THREAD

**Issue by hugovom** [GobiernoFacil/agentes-v2#157]
Desde el admin, cuando meten tiempo, ¿sería mejor que metieran minutos / horas? y que el sistema calculé duración de cada semana?

![screen shot 2018-01-15 at 5 03 45 pm](https://user-images.githubusercontent.com/2445854/34964957-383291c8-fa16-11e7-9f94-7f1eaed66575.png)

**Comment by CarlosOsorio** [comment]
Se puede manejar horas enteras y que el mínimo sea una hora. ¿no?

**Comment by hugovom** [comment]
el problema es que en actividades, hay videos de 5 minutos

**Comment by CarlosOsorio** [comment]
Pues entonces, sí sería agregar la unidad de medida (minutos u horas) y ya con eso se puede calcular.

**Comment by hugovom** [comment]
va
