### ISSUE TITLE
Fellow: Agregar funcionalidad en dashboard para abrir/cerrar paneles de módulos

### ISSUE THREAD

**Issue by hugovom** [GobiernoFacil/agentes-v2#160]
<img width="728" alt="screen shot 2018-01-15 at 5 47 41 pm" src="https://user-images.githubusercontent.com/2445854/34965762-3491846a-fa1c-11e7-81f6-09e2cb4c9365.png">

**Comment by hugovom** [comment]
Modificar en: `resources/views/fellow/dashboard_layout/dash_module.blade.php`

**Comment by elcoruco** [comment]
listo, se resolvió en resources/views/fellow/dashboard.blade.php

En el js, hay un par de variables que asignan la clase al botón, ahí se puede cambiar la clase cuando cierra y abre (supongo que de ahí se controla la flecha en SVG)

son estas variables:
```
open_class = "ap-show",
close_class = "ap-show",
```
