### ISSUE TITLE
Agregar diseño en dashboard fellow

### ISSUE THREAD

**Issue by CarlosOsorio** [GobiernoFacil/agentes-v2#67]
Falta agregar diseño a Foros, Mensajes y foros dentro de actividades, así como el diseño cuando una actividad, módulo o sesión se encuentra bloqueado.

**Comment by hugovom** [comment]
@CarlosOsorio las sesiones no son secuenciales, solo los módulos

**Comment by CarlosOsorio** [comment]
@hugovom las sesiones cuenta con fecha, no sé si eso se tomará en cuenta para activarlas o desactivarlas.

**Comment by hugovom** [comment]
buena pregunta, voy a averiguarlo
