### ISSUE TITLE
fellow: Foros en servidor de producción

### ISSUE THREAD

**Issue by hugovom** [GobiernoFacil/agentes-v2#73]
Por alguna extraña razón los dos foros que hay los está tomando como que son del estado, el foto de actividad viene con sesión null, tal vez algo se guardó mal pero recuerdo que si veía la sesión hace 2 días.

![screen shot 2017-06-01 at 2 00 47 pm](https://cloud.githubusercontent.com/assets/2445854/26696059/be0eda06-46d2-11e7-877c-1265a097fb0b.png)

**Comment by CarlosOsorio** [comment]
@hugovom Se actualizó la base de datos del servidor para quitar el error.
