### ISSUE TITLE
Diseño dashboard de facilitadores

### ISSUE THREAD

**Issue by hugovom** [GobiernoFacil/agentes-v2#80]

**Comment by ArgentinaVelasco** [comment]
¿Qué tareas o que pueden ver los facilitadores?

**Comment by hugovom** [comment]
- Foros
- Mensajes 
- Noticias 
- Actividades en las que participan

**Comment by ArgentinaVelasco** [comment]
Mockup > sistema > facilitadores > mockup_dashboard_facilitador.png
